# Generated by Django 3.2.6 on 2021-08-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_comment_commentauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentAuthor',
            field=models.CharField(default='hello', max_length=50),
            preserve_default=False,
        ),
    ]
