# Generated by Django 3.2.6 on 2021-08-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_commentauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjectName',
            field=models.CharField(max_length=200),
        ),
    ]
